/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.13.0.56.2 */
/* Module Version: 5.4 */
/* Wed Jan 15 19:28:31 2025 */

/* parameterized module instance */
rom_8x4096 __ (.Address( ), .OutClock( ), .OutClockEn( ), .Reset( ), 
    .Q( ));
