/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.12.1.454 */
/* Module Version: 5.7 */
/* Fri Jan 05 17:02:25 2024 */

/* parameterized module instance */
pll __ (.CLKI( ), .CLKOP( ));
