//Verilog testbench template generated by SCUBA Diamond (64-bit) 3.13.0.56.2
`timescale 1 ns / 1 ps
module tb_pll;
    
    reg OutClock = 0;
    
    wire  clock;

   

    pll u1 (.CLKI(OutClock ), .CLKOP(clock )
    );

initial begin
    // Generate a clock signal
    forever #5 OutClock = ~OutClock;
end

initial begin
    // Simulation time: 1000 ns
    #1000;
    $stop;
end
endmodule